import type { StudioTask, TaskDraft } from "./types";

export const emptyTaskDraft: TaskDraft = {
  title: "",
  description: "",
  category: "Trabalho",
  priority: "Média",
  estimatedTime: "30min",
  customMinutes: 45,
  status: "A fazer",
  day: "Segunda",
  specificDate: "",
  notes: "",
};

export const defaultTasks: StudioTask[] = [
  {
    id: "tarefa-inicial-1",
    title: "Revisar roteiro da próxima gravação",
    description: "Revisar a versão final antes da reunião de produção.",
    category: "Trabalho",
    priority: "Alta",
    estimatedTime: "1h",
    customMinutes: 60,
    status: "A fazer",
    day: "Segunda",
    specificDate: "",
    notes: "Confirmar versões e observações do diretor.",
    createdAt: "2026-06-07T09:00:00.000Z",
  },
  {
    id: "tarefa-inicial-2",
    title: "Confirmar locação e horário de call",
    description: "",
    category: "Trabalho",
    priority: "Urgente",
    estimatedTime: "30min",
    customMinutes: 30,
    status: "Em progresso",
    day: "Terça",
    specificDate: "",
    notes: "",
    createdAt: "2026-06-07T09:05:00.000Z",
  },
  {
    id: "tarefa-inicial-3",
    title: "Organizar arquivos do último projeto",
    description: "",
    category: "Rotina",
    priority: "Baixa",
    estimatedTime: "2h",
    customMinutes: 120,
    status: "Concluída",
    day: "Sexta",
    specificDate: "",
    notes: "Separar selects e backups.",
    createdAt: "2026-06-07T09:10:00.000Z",
  },
];
