create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  anonymous_id uuid not null,
  event_name text not null,
  tool text not null,
  device_type text not null,
  app_version text not null,
  created_at timestamptz not null default now()
);

create index if not exists usage_events_created_at_idx
  on public.usage_events(created_at desc);

create index if not exists usage_events_tool_created_idx
  on public.usage_events(tool, created_at desc);

alter table public.usage_events enable row level security;

drop policy if exists usage_insert on public.usage_events;
create policy usage_insert
on public.usage_events
for insert
to authenticated
with check ((select auth.uid()) is not null);

revoke all on table public.usage_events from anon, authenticated;
grant insert on table public.usage_events to authenticated;
grant usage, select on sequence public.usage_events_id_seq to authenticated;
